apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: angular-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-deployment
  template:
    metadata:
      labels:
        app: angular-deployment
    spec:
      containers:
        - name: frontendcomposecontainer
          image: frontendcomposeimg
          ports:
            - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: LoadBalancer
  selector:
    app: angular-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
